language: generic

os: osx
osx_image:
  - xcode10.3
  - xcode11.6
  - xcode12.5
  - xcode13.2

before_install:
  - travis_wait brew update
  - brew uninstall --force --ignore-dependencies boost-python37
  - travis_wait brew install --force --build-bottle Formula/boost-python37.rb || exit 1
  - travis_wait brew bottle Formula/boost-python37.rb || exit 1

branches:
  except:
    - /^(?:unstable)$/
